### ISSUE TITLE
This repository is over its data quota

### ISSUE THREAD

**Issue by asivura** [AARSynth/Dataset#2]
Hi there,

We're two Stanford student researchers who're very interested in generating the Google Play Appstore review responses task and tackling this challenge via an ML class (CS229 http://cs229.stanford.edu) project at Stanford.

I have an error when clone the repo:

```Error downloading object: Cleaned/AllNoReplies.txt (57e40cc): Smudge error: Error downloading Cleaned/AllNoReplies.txt (57e40cca5ed922aa26bb6f7c9b360cd638d547e9be2abc19ee761ef3529b59d2): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.```

Is it a chance to share the data in any other way or we can buy a gift card for you to extend the GitHub quota temporary.

Many thanks for considering my request.

Best,
Alexander Sivura

**Comment by ufarooq** [comment]
Hi @asivura, I have uploaded files on Google Drive, you can get them using the following link.  https://drive.google.com/drive/folders/1I00-knyIDK7f6vnDSoUlLydwGs7BFvvm?usp=sharing

**Comment by asivura** [comment]
Thanks a lot!
